# Generated by Django 5.1.3 on 2024-12-05 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pagina_web", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tarjeta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("descripcion", models.TextField()),
                ("imagen", models.ImageField(upload_to="tarjetas/")),
            ],
        ),
    ]
